---
title: "Aseess the causal effect on diabetes"
author: "Tianyang Jiang, Changhao Jiang, and Liuye Huang"
date: "`r Sys.Date()`"
output: 
  html_document:
    theme: journal
    highlight: tango
    toc: true
    toc_depth: 3
    toc_float:
      collapsed: true
      smooth_scroll: false
    number_sections: false
  df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Setup

## R library and data input
```{r}
library(data.table)
library(randomForest)
library(dplyr)
```

# Summarize data

## Load diabetes data
```{r}
data_dir <- "~/Documents/STAT566/Project"

balanced_diabetes <- fread(file.path(data_dir, "diabetes_binary_5050split_health_indicators_BRFSS2015.csv"))
diabetes <- fread(file.path(data_dir,"diabetes_binary_health_indicators_BRFSS2015.csv"))

dim(balanced_diabetes)
balanced_diabetes[1:3,]

dim(diabetes)
diabetes[1:3,]
```

## Find scores with random forest

```{r, warning=FALSE}
set.seed(1)
fit.forest= randomForest(Diabetes_binary ~ HvyAlcoholConsump + Smoker + 
                           PhysActivity + Fruits + Veggies,
                         data = balanced_diabetes, na.action = na.roughfix)
importance(fit.forest)

w1 = importance(fit.forest)[1]/sum(importance(fit.forest))
w2 = importance(fit.forest)[2]/sum(importance(fit.forest))
w3 = importance(fit.forest)[3]/sum(importance(fit.forest))
w4 = importance(fit.forest)[4]/sum(importance(fit.forest))
w5 = importance(fit.forest)[5]/sum(importance(fit.forest))

score = -diabetes$HvyAlcoholConsump * w1 - diabetes$Smoker * w2 + 
  diabetes$PhysActivity * w3 + diabetes$Fruits * w4 + diabetes$Veggies * w5
summary(score)
hist(score)
```

```{r}
diabetes %>% filter(score > 0.4112) %>% summarise(n=n())
diabetes %>% filter(score <= 0.4112) %>% summarise(n=n())

diabetes$score = score
sum(diabetes[diabetes$score<=mean(diabetes$score),]$Diabetes_binary==1)
sum(diabetes[diabetes$score>mean(diabetes$score),]$Diabetes_binary==1)
```

# Fit logistic regression

```{r}
lm(score)
```

# Regression Adjustment





