---
title: "Aseess the causal effect on diabetes"
author: "Changhao Jiang, Tianyang Jiang, and Liuye Huang"
date: "`r Sys.Date()`"
output: 
  html_document:
    theme: journal
    highlight: tango
    toc: true
    toc_depth: 3
    toc_float:
      collapsed: true
      smooth_scroll: false
    number_sections: false
  df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Setup

## R library and data input
```{r}
library(data.table)
library(randomForest)
library(sandwich)
library(car)
```

# Summarize data

## Load diabetes data
```{r}
data_dir <- "~/Documents/STAT566/Project"

balanced_diabetes <- fread(file.path(data_dir, "diabetes_binary_5050split_health_indicators_BRFSS2015.csv"))
diabetes <- fread(file.path(data_dir,"diabetes_binary_health_indicators_BRFSS2015.csv"))

dim(balanced_diabetes)
balanced_diabetes[1:3,]

dim(diabetes)
diabetes[1:3,]
```

## Find scores with random forest

```{r, warning=FALSE}
set.seed(1)
fit.forest= randomForest(Diabetes_binary ~ HvyAlcoholConsump + Smoker + 
                           PhysActivity + Fruits + Veggies,
                         data = balanced_diabetes, na.action = na.roughfix)
importance(fit.forest)

w1 = importance(fit.forest)[1] / sum(importance(fit.forest))
w2 = importance(fit.forest)[2] / sum(importance(fit.forest))
w3 = importance(fit.forest)[3] / sum(importance(fit.forest))
w4 = importance(fit.forest)[4] / sum(importance(fit.forest))
w5 = importance(fit.forest)[5] / sum(importance(fit.forest))

diabetes$score = -diabetes$HvyAlcoholConsump * w1 - diabetes$Smoker * w2 + 
  diabetes$PhysActivity * w3 + diabetes$Fruits * w4 + diabetes$Veggies * w5

summary(diabetes$score)
hist(diabetes$score)
```

## Check the number of scores

```{r}
mean_score <- mean(diabetes$score)

sum(diabetes$score <= mean_score)
sum(diabetes$score > mean_score)

sum(diabetes[diabetes$score <= mean_score,]$Diabetes_binary == 1)
sum(diabetes[diabetes$score > mean_score,]$Diabetes_binary == 1)

diabetes$scoreCat <- ifelse(diabetes$score > mean_score, 1, 0)
```

# Fit logistic regression

## Only consider exposure

```{r}
model_score <- glm(Diabetes_binary ~ scoreCat, data = diabetes, 
                   family = binomial)
summary(model_score)

Confint(model_score, vcov. = vcovHC(model_score, type = "HC0")) 
```

## Regression Adjustment
```{r}
model_score_adj <- glm(Diabetes_binary ~ scoreCat + Sex + Age + Income,
                       data = diabetes, family = binomial)
summary(model_score_adj)

Confint(model_score_adj, vcov. = vcovHC(model_score_adj, type = "HC0"))
```

## Combine the Results

```{r}
results <- summary(model_score)$coefficients

rownames(results) <- c("score", "adjusted score")

results <- results[, c("Estimate", "Std. Error", "z value")]
colnames(results) <- c("Estimate", "2.5 %", "97.5 %")

results["score", ] <- c(-0.5980872, -0.620951, -0.5752233)
results["adjusted score", ] <- c(-0.3774651, -0.4016496, -0.3532806)

knitr::kable(results, digits = c(4, 4, 4), align = "c", caption = "Adjustment Results")
```


